---
# Tasks for installing and configuring the Java programming language


- name: "Run assertions"
  ansible.utils.validate:
    data: "{{ java }}"
    criteria: "{{ lookup('file', 'assertions/criteria/java-criteria.json') | from_json }}"
    engine: ansible.utils.jsonschema
  run_once: yes
  delegate_to: localhost
  when:
    - java is defined


- name: "Install versions"
  ansible.builtin.include_tasks: install.yml
  loop: "{{ java }}"
  loop_control:
    loop_var: version
  when:
    - java is defined
