---
# Tasks for installing and configuring the Java programming language


- name: Assert necessary variables and environment for Java installation
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost


- name: Install OpenJDK
  ansible.builtin.import_tasks: vendors/openjdk.yml
  when: java_vendor == "openjdk"


- name: Configure Java on global level
  ansible.builtin.import_tasks: global.yml
  when: java_global == true


- name: Configure Java on user level
  ansible.builtin.include_tasks: users.yml
  loop: "{{ java_users }}"
  loop_control:
    loop_var: java_user
  when: java_global == false
